# Week 2 Exercises: Python Recap

## Exercises 1-3
See exercise sheet 2 in Obsidian

## Exercise 4: NumpPy package

In [34]:
import numpy as np

matrix = np.loadtxt("matrix.txt", usecols=range(4), delimiter=",")

print(matrix)

A = matrix[:, :-1]
b = matrix[:, -1]

print("A:\n", A)
print("b:\n", b)

linear_solve = np.linalg.solve(A, b)
print(linear_solve)

[[ 1.  2.  3.  4.]
 [ 6.  9. 12.  7.]
 [ 2.  0.  9. 10.]]
A:
 [[ 1.  2.  3.]
 [ 6.  9. 12.]
 [ 2.  0.  9.]]
b:
 [ 4.  7. 10.]
[-5.09090909  1.18181818  2.24242424]


## Exercise 5: SciPy package

In [ ]:
import scipy as sp
from scipy.optimize import fsolve

points = np.loadtxt("points.txt")
x = points[:, 0]
y = points[:, 1]

x: [-20. -19. -18. -17. -16. -15. -14. -13. -12. -11. -10.  -9.  -8.  -7.
  -6.  -5.  -4.  -3.  -2.  -1.   0.   1.   2.   3.   4.   5.   6.   7.
   8.   9.  10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]
y: [-2.35552551e+04 -2.01733974e+04 -1.71323838e+04 -1.44110122e+04
 -1.19955143e+04 -9.86656080e+03 -8.00320517e+03 -6.39133487e+03
 -5.01146273e+03 -3.84672650e+03 -2.87544385e+03 -2.08452334e+03
 -1.45139187e+03 -9.62410182e+02 -5.95527093e+02 -3.36594621e+02
 -1.64079981e+02 -6.23865272e+01 -1.14248728e+01  3.06432478e+00
  4.20759723e+00  6.21613879e+00  2.76438529e+01  8.81769919e+01
  2.04004215e+02  3.93974857e+02  6.76404801e+02  1.06792294e+03
  1.58779539e+03  2.25439824e+03  3.08445831e+03  4.09565592e+03
  5.30724684e+03  6.73759055e+03  8.40459369e+03  1.03235165e+04
  1.25152158e+04  1.49981211e+04  1.77885813e+04  2.09044423e+04]
